<?php 
// Config generated by ConfigMan 0.1
// Timestamp: 23 04 2017 15:33:24
// Server IP: 185.10.49.231 alias projects.levls.be
return unserialize('a:1:{s:11:"Train trips";a:2:{i:0;s:5:"Trips";i:1;s:4:"Logs";}}');
?>